#!/usr/bin/env bash
# Свой Supabase на сервере (deploy/supabase/compose.yaml) — одна точка входа:
#
#   scripts/supabase.sh init https://supabase.ailshan.jhfasd.space https://ailshan.jhfasd.space
#                      # один раз: генерирует секреты и ключи в файл SUPABASE_ENV_FILE
#   scripts/supabase.sh up            # поднять/обновить стек и накатить миграции
#   scripts/supabase.sh studio        # то же, плюс Studio (SSH-туннель к 127.0.0.1:54321)
#   scripts/supabase.sh migrate       # только миграции из supabase/migrations
#   scripts/supabase.sh create-admin you@example.com 'пароль'
#   scripts/supabase.sh keys          # ключи для .env и secrets Ailshan
#   scripts/supabase.sh backup        # pg_dump + файлы Storage → AILSHAN_BACKUP_DIR
#   scripts/supabase.sh psql          # консоль базы
#   scripts/supabase.sh ps | logs [сервис] | down
set -Eeuo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SECRETS_FILE="${SUPABASE_ENV_FILE:-/opt/ailshan/secrets/supabase.env}"
BACKUP_DIR="${AILSHAN_BACKUP_DIR:-/opt/ailshan/backups}"
BACKUP_KEEP_DAYS="${AILSHAN_BACKUP_KEEP_DAYS:-14}"
COMPOSE_FILE="$APP_DIR/deploy/supabase/compose.yaml"
PROJECT="ailshan-supabase"

usage() { sed -n '2,15p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 1; }

compose() {
  [[ -f "$SECRETS_FILE" ]] || { echo "ERROR: секреты не найдены: $SECRETS_FILE — сначала scripts/supabase.sh init <api-url> <site-url>"; exit 1; }
  docker compose --env-file "$SECRETS_FILE" -f "$COMPOSE_FILE" "$@"
}

# psql внутри контейнера базы; пароль берётся из PGPASSWORD контейнера
dbsql() { compose exec -T db psql -U postgres -h 127.0.0.1 -d postgres -v ON_ERROR_STOP=1 -q "$@"; }

b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }

# JWT HS256 с ролью — формат «старых» ключей Supabase (anon / service_role)
make_jwt() {
  local role="$1" secret="$2" now exp header payload signing
  now="$(date +%s)"; exp=$((now + 10 * 365 * 24 * 3600))
  header="$(printf '{"alg":"HS256","typ":"JWT"}' | b64url)"
  payload="$(printf '{"role":"%s","iss":"supabase","iat":%s,"exp":%s}' "$role" "$now" "$exp" | b64url)"
  signing="$header.$payload"
  printf '%s.%s' "$signing" "$(printf '%s' "$signing" | openssl dgst -sha256 -hmac "$secret" -binary | b64url)"
}

wait_healthy() {
  local name deadline=$((SECONDS + 300)) status
  for name in "$@"; do
    while :; do
      status="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$name" 2>/dev/null || true)"
      [[ "$status" == "healthy" ]] && break
      if (( SECONDS > deadline )); then
        echo "ERROR: $name не стал healthy (сейчас: ${status:-нет контейнера})"
        compose ps; compose logs --no-color --tail=60 "${name#supabase-}"
        exit 1
      fi
      sleep 3
    done
  done
}

load_secrets() {
  [[ -f "$SECRETS_FILE" ]] || { echo "ERROR: секреты не найдены: $SECRETS_FILE"; exit 1; }
  set -a; # shellcheck disable=SC1090
  source "$SECRETS_FILE"; set +a
}

cmd_init() {
  local public_url="${1:-}" site_url="${2:-}"
  [[ -n "$public_url" && -n "$site_url" ]] || { echo "usage: scripts/supabase.sh init <публичный URL API> <URL сайта>"; exit 1; }
  command -v openssl >/dev/null || { echo "ERROR: нужен openssl"; exit 1; }
  if [[ -e "$SECRETS_FILE" ]]; then
    echo "ERROR: $SECRETS_FILE уже существует. Новые секреты не подойдут к уже инициализированной базе — удалите файл и том db_data, только если стек ещё не поднимали."
    exit 1
  fi
  mkdir -p "$(dirname "$SECRETS_FILE")"; chmod 700 "$(dirname "$SECRETS_FILE")"

  # Только hex/латиница: значения проходят через eval в entrypoint Kong и через URL
  local pg_pass jwt_secret anon service dash_pass meta_key
  pg_pass="$(openssl rand -hex 24)"
  jwt_secret="$(openssl rand -hex 32)"
  anon="$(make_jwt anon "$jwt_secret")"
  service="$(make_jwt service_role "$jwt_secret")"
  dash_pass="$(openssl rand -hex 16)"
  meta_key="$(openssl rand -hex 16)"

  umask 077
  cat > "$SECRETS_FILE" <<EOF
# Secrets of the self-hosted Supabase (generated by scripts/supabase.sh init).
# Changing POSTGRES_PASSWORD or JWT_SECRET after the first start breaks the
# stack: roles and tokens were created with these values.
SUPABASE_PUBLIC_URL=${public_url%/}
SITE_URL=${site_url%/}

POSTGRES_PASSWORD=$pg_pass
JWT_SECRET=$jwt_secret
JWT_EXPIRY=3600
ANON_KEY=$anon
SERVICE_ROLE_KEY=$service

# Studio (basic auth on Kong); reachable only via SSH tunnel to 127.0.0.1:KONG_HOST_PORT
DASHBOARD_USERNAME=ailshan
DASHBOARD_PASSWORD=$dash_pass
PG_META_CRYPTO_KEY=$meta_key

# Ports on the server loopback (same numbers as the local CLI stack)
KONG_HOST_PORT=54321
POSTGRES_HOST_PORT=54322

# Auth: signup closed, no email confirmation. Fill SMTP to enable password recovery mail.
DISABLE_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
SMTP_ADMIN_EMAIL=
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_SENDER_NAME=Ailshan
EOF
  echo "Секреты записаны: $SECRETS_FILE"
  echo "Дальше: scripts/supabase.sh up"
}

cmd_migrate() {
  wait_healthy supabase-db supabase-auth supabase-storage
  # Та же таблица, что ведёт Supabase CLI: `supabase db push` через туннель
  # увидит уже применённые версии.
  dbsql <<'SQL'
create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (
  version text not null primary key,
  statements text[],
  name text
);
SQL
  local applied file base version name count=0
  applied="$(dbsql -At -c "select version from supabase_migrations.schema_migrations")"
  for file in "$APP_DIR"/supabase/migrations/*.sql; do
    base="$(basename "$file" .sql)"; version="${base%%_*}"; name="${base#*_}"
    if grep -qx "$version" <<<"$applied"; then continue; fi
    echo "→ миграция $base"
    dbsql -1 -f - < "$file"
    # Через stdin, а не -c: подстановка :'v' работает только в обычном вводе psql
    dbsql -v v="$version" -v n="$name" <<<"insert into supabase_migrations.schema_migrations (version, name) values (:'v', :'n');"
    count=$((count + 1))
  done
  echo "Миграции: применено $count, всего $(dbsql -At -c 'select count(*) from supabase_migrations.schema_migrations')."
}

cmd_up() {
  local profile=()
  [[ "${1:-}" == "--studio" ]] && profile=(--profile studio)
  docker network inspect edge >/dev/null 2>&1 || { echo "ERROR: нет docker-сети edge (её создаёт установка InstaWorker: docker network create edge)"; exit 1; }
  compose "${profile[@]}" config --quiet
  compose "${profile[@]}" up -d --remove-orphans
  wait_healthy supabase-db supabase-auth supabase-rest supabase-storage supabase-kong
  cmd_migrate
  [[ ${#profile[@]} -gt 0 ]] && wait_healthy supabase-meta supabase-studio
  compose ps
}

cmd_create_admin() {
  local email="${1:-}" password="${2:-}" port code body
  [[ -n "$email" && -n "$password" ]] || { echo "usage: scripts/supabase.sh create-admin <email> <пароль>"; exit 1; }
  load_secrets
  port="${KONG_HOST_PORT:-54321}"
  wait_healthy supabase-kong
  body="$(mktemp)"
  # JSON без jq: email и пароль без кавычек и обратных слэшей
  [[ "$email$password" != *[\"\\]* ]] || { echo "ERROR: кавычки и обратный слэш в email/пароле не поддерживаются"; exit 1; }
  code="$(curl -s -o "$body" -w '%{http_code}' -X POST "http://127.0.0.1:$port/auth/v1/admin/users" \
    -H "apikey: $SERVICE_ROLE_KEY" -H "Authorization: Bearer $SERVICE_ROLE_KEY" -H "Content-Type: application/json" \
    -d "{\"email\":\"$email\",\"password\":\"$password\",\"email_confirm\":true}")"
  if [[ "$code" == "200" || "$code" == "201" ]]; then
    echo "Пользователь создан: $email"
  elif [[ "$code" == "422" ]] && grep -qi "already\|exists\|registered" "$body"; then
    echo "Пользователь уже есть: $email — обновляю роль"
  else
    echo "ERROR: auth ответил $code: $(cat "$body")"; rm -f "$body"; exit 1
  fi
  rm -f "$body"
  # Триггер handle_new_user уже создал профиль; поднимаем до супер-админа
  dbsql -v email="$email" <<<"update public.profiles set role = 'super_admin', onboarding_completed = true where email = :'email';"
  echo "Супер-админ готов: $email (вход: $SITE_URL/login)"
}

cmd_keys() {
  load_secrets
  cat <<EOF
# → в /opt/ailshan/app/.env
NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_PUBLIC_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY

# → в /opt/ailshan/secrets/ailshan.env
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
EOF
}

cmd_backup() {
  local ts volume
  ts="$(date +%Y%m%d-%H%M%S)"
  mkdir -p "$BACKUP_DIR"; chmod 700 "$BACKUP_DIR"
  wait_healthy supabase-db
  # supabase_admin — суперпользователь образа: дамп включает auth и storage
  compose exec -T db pg_dump -U supabase_admin -h 127.0.0.1 -d postgres -Fc > "$BACKUP_DIR/db-$ts.dump"
  volume="$(docker volume ls -q --filter "label=com.docker.compose.project=$PROJECT" --filter "label=com.docker.compose.volume=storage_data")"
  [[ -n "$volume" ]] || { echo "ERROR: том storage_data не найден"; exit 1; }
  docker run --rm -v "$volume:/data:ro" -v "$BACKUP_DIR:/backup" alpine:3.20 tar czf "/backup/storage-$ts.tgz" -C /data .
  find "$BACKUP_DIR" -maxdepth 1 -type f \( -name 'db-*.dump' -o -name 'storage-*.tgz' \) -mtime "+$BACKUP_KEEP_DAYS" -delete
  ls -la "$BACKUP_DIR" | grep -E "db-$ts|storage-$ts"
  echo "Восстановление: pg_restore -U supabase_admin -d postgres --clean --if-exists db-$ts.dump; tar xzf storage-$ts.tgz в том storage_data"
}

case "${1:-}" in
  init)         cmd_init "${2:-}" "${3:-}" ;;
  up)           cmd_up ;;
  studio)       cmd_up --studio ;;
  migrate)      cmd_migrate ;;
  create-admin) cmd_create_admin "${2:-}" "${3:-}" ;;
  keys)         cmd_keys ;;
  backup)       cmd_backup ;;
  psql)         compose exec db psql -U postgres -h 127.0.0.1 -d postgres ;;
  ps)           compose ps ;;
  logs)         shift; compose logs --no-color --tail=100 "$@" ;;
  down)         compose --profile studio down ;;
  *)            usage ;;
esac
